In [2]:
from palmerpenguins import load_penguins
import pandas as pd

In [3]:
df = load_penguins()
df.head()

  species     island  bill_length_mm  ...  body_mass_g     sex  year
0  Adelie  Torgersen            39.1  ...       3750.0    male  2007
1  Adelie  Torgersen            39.5  ...       3800.0  female  2007
2  Adelie  Torgersen            40.3  ...       3250.0  female  2007
3  Adelie  Torgersen             NaN  ...          NaN     NaN  2007
4  Adelie  Torgersen            36.7  ...       3450.0  female  2007

[5 rows x 8 columns]

In [ ]:
# Get info about the dataset (number of rows, columns, data types, etc.)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   island             344 non-null    str
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    str
 7   year               344 non-null    int64
dtypes: float64(4), int64(1), str(3)
memory usage: 21.6 KB

In [ ]:
# Check for missing values in the dataset
df.isna().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
year                  0
dtype: int64

In [ ]:
# Get a summary of the dataset
# Distribution of numerical features, count of unique values for categorical features, etc.
df.describe(include='all')

       species  island  bill_length_mm  ...  body_mass_g   sex         year
count      344     344      342.000000  ...   342.000000   333   344.000000
unique       3       3             NaN  ...          NaN     2          NaN
top     Adelie  Biscoe             NaN  ...          NaN  male          NaN
freq       152     168             NaN  ...          NaN   168          NaN
mean       NaN     NaN       43.921930  ...  4201.754386   NaN  2008.029070
std        NaN     NaN        5.459584  ...   801.954536   NaN     0.818356
min        NaN     NaN       32.100000  ...  2700.000000   NaN  2007.000000
25%        NaN     NaN       39.225000  ...  3550.000000   NaN  2007.000000
50%        NaN     NaN       44.450000  ...  4050.000000   NaN  2008.000000
75%        NaN     NaN       48.500000  ...  4750.000000   NaN  2009.000000
max        NaN     NaN       59.600000  ...  6300.000000   NaN  2009.000000

[11 rows x 8 columns]